[cosmic-ray]
module-path = "python_programs/hanoi.py"
python-version = ""
timeout = 10.0
excluded-modules = []
test-command = "pytest python_tests/test_hanoi.py"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []

