[cosmic-ray]
module-path = "python_programs/lcs_length.py"
python-version = ""
timeout = 10.0
excluded-modules = []
test-command = "python -x pytest python_tests/test_lcs_length.py"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []

